title: "CTAP"
email: geral@ctap.pt
description: "Clube de Tiro com Arco do Porto "
baseurl: ""        # vazio para site do utilizador
url: "https://rmmossso.github.io"
theme: minima
plugins:
  - jekyll-feed
